### ISSUE TITLE
Is time out error a bad thing and are these votes going through?  how can i tell?

### ISSUE THREAD

**Issue by darkwolf7887** [pomodori92/voteBot#2]
TimeoutError: Waiting for selector `#PDI_answer58005153.css-radiobutton.pds-radiobutton` failed: Waiting failed: 30000ms exceeded
    at Timeout.<anonymous> (C:\Users\beast\node_modules\puppeteer-core\lib\cjs\puppeteer\common\WaitTask.js:59:37)
    at listOnTimeout (node:internal/timers:573:17)
    at process.processTimers (node:internal/timers:514:7)

**Comment by pomodori92** [comment]
Hi, I haven't updated this application for a long time.
How can I reproduce this error?

**Comment by darkwolf7887** [comment]
Site =
https://www.rgj.com/story/sports/high-school/2023/10/24/champion-chevrolet-athlete-of-the-week-nominees-for-oct-10-16-vote-now/71291492007/

iD = in attached pic

**Comment by pomodori92** [comment]
I can't see a poll on that page and there is no attached picture.

**Comment by pomodori92** [comment]
It's another site and I can't see polls. If you have other issues, open another issue.
